version: '2'
services:
  web:
    build: .
    env_file: .env
    links:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/opt/webapp
    tty: true
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  worker:
    image: image_service_web:latest
    env_file: .env
    command: python3 worker.py

