version: '2'
services:
  web:
    build: .
    env_file: .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/webapp/.google_config.json
    links:
      - redis_worker
      - redis_db
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/opt/webapp
    tty: true
  redis_worker:
    image: redis:alpine
    ports:
      - "6379:6379"
  redis_db:
    image: redis:alpine
    ports:
      - "6380:6379"
  worker:
    image: image_service_web:latest
    env_file: .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/webapp/.google_config.json
    command: python3 worker.py
  thumbnailworker:
    image: image_service_web:latest
    env_file: .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/webapp/.google_config.json
    command: python3 thumbnailworker.py
